name: pytest

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger pytest on (e.g., main, master)

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your dependencies file name (if applicable)

      - name: Run pytest
        run: pytest  # You can specify additional pytest options here
